### ISSUE TITLE
Background image path breaks on local server

### ISSUE THREAD

**Issue by rmkane** [DrKain/csgo-sticker-signature-generator#5]
The background image load correctly at:

```
http://localhost/csgo-sticker-signature
```

But it fails to load at:

```
http://localhost/csgo-sticker-signature/index.html
```

This is because the default background image path is concatenating the path to the image with the current location's path name.

This produces a 404 (Resource not found) error; which breaks redrawing on the canvas.

```
http://localhost/csgo-sticker-signature/index.htmlimages/nobg.png
```

**Comment by rmkane** [comment]
Added a pull request: [Pull Request #6 ](https://github.com/TryHardHusky/csgo-sticker-signature-generator/pull/6)

**Comment by DrKain** [comment]
Thanks for the commit, But this generator isn't designed to work on a local server.  
As designed, You can use the generator at the following URL.  
http://tryhardhusky.github.io/csgo-sticker-signature-generator/

**Comment by rmkane** [comment]
OK, so the "local server" part was just that not all servers are configured to rewrite `my-website.com/index.html` to `mywebsite.com/`

The following link is broken, but valid:

> http://tryhardhusky.github.io/csgo-sticker-signature-generator/index.html
