### ISSUE TITLE
Are we allowed to modify and upload this on our own domain?

### ISSUE THREAD

**Issue by nhojj** [DrKain/csgo-sticker-signature-generator#8]
The title says it all :)

**Comment by DrKain** [comment]
See the [LICENSE](https://github.com/TryHardHusky/csgo-sticker-signature-generator/blob/gh-pages/LICENSE)  

>  Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.  
  
If you want your own generator, I can make you one. Contact me on [steam](http://steamcommunity.com/id/kainsir/)
