### ISSUE TITLE
Some problem in China

### ISSUE THREAD

**Issue by cherinyy** [DrKain/csgo-sticker-signature-generator#9]
Could you change the link in README.MD to an HTTPS URL?
You maybe have heard of China’s national firewall[(Great Firewall)](https://en.wikipedia.org/wiki/Great_Firewall)
Although it did not completely block GitHub, it blocked communication for HTTP links. This limitation also appears on Steam(Store, Community). May also need to modify the Steam profile link on the page.

And could you use [jsDelivr](https://www.jsdelivr.com/) to be Open Source CDN?

They purchased Cloudflare's enterprise services, so there are also deployed servers in China.

**Comment by DrKain** [comment]
This project is discontinued but I've updated the readme links for you anyway.  
I'll look into jsDelivr another time
